# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stream_pb2 as stream__pb2


class JreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStream = channel.unary_stream(
                '/Jreeter/GetStream',
                request_serializer=stream__pb2.StreamReqData.SerializeToString,
                response_deserializer=stream__pb2.StreamResData.FromString,
                )
        self.PutStream = channel.stream_unary(
                '/Jreeter/PutStream',
                request_serializer=stream__pb2.StreamReqData.SerializeToString,
                response_deserializer=stream__pb2.StreamResData.FromString,
                )
        self.AllStream = channel.stream_stream(
                '/Jreeter/AllStream',
                request_serializer=stream__pb2.StreamReqData.SerializeToString,
                response_deserializer=stream__pb2.StreamResData.FromString,
                )


class JreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStream,
                    request_deserializer=stream__pb2.StreamReqData.FromString,
                    response_serializer=stream__pb2.StreamResData.SerializeToString,
            ),
            'PutStream': grpc.stream_unary_rpc_method_handler(
                    servicer.PutStream,
                    request_deserializer=stream__pb2.StreamReqData.FromString,
                    response_serializer=stream__pb2.StreamResData.SerializeToString,
            ),
            'AllStream': grpc.stream_stream_rpc_method_handler(
                    servicer.AllStream,
                    request_deserializer=stream__pb2.StreamReqData.FromString,
                    response_serializer=stream__pb2.StreamResData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Jreeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Jreeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Jreeter/GetStream',
            stream__pb2.StreamReqData.SerializeToString,
            stream__pb2.StreamResData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Jreeter/PutStream',
            stream__pb2.StreamReqData.SerializeToString,
            stream__pb2.StreamResData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AllStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Jreeter/AllStream',
            stream__pb2.StreamReqData.SerializeToString,
            stream__pb2.StreamResData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
