# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stream.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\010../proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cstream.proto\"\x1d\n\rStreamReqData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1d\n\rStreamResData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x98\x01\n\x07Jreeter\x12-\n\tGetStream\x12\x0e.StreamReqData\x1a\x0e.StreamResData0\x01\x12-\n\tPutStream\x12\x0e.StreamReqData\x1a\x0e.StreamResData(\x01\x12/\n\tAllStream\x12\x0e.StreamReqData\x1a\x0e.StreamResData(\x01\x30\x01\x42\nZ\x08../protob\x06proto3'
)




_STREAMREQDATA = _descriptor.Descriptor(
  name='StreamReqData',
  full_name='StreamReqData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='StreamReqData.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=45,
)


_STREAMRESDATA = _descriptor.Descriptor(
  name='StreamResData',
  full_name='StreamResData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='StreamResData.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['StreamReqData'] = _STREAMREQDATA
DESCRIPTOR.message_types_by_name['StreamResData'] = _STREAMRESDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamReqData = _reflection.GeneratedProtocolMessageType('StreamReqData', (_message.Message,), {
  'DESCRIPTOR' : _STREAMREQDATA,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamReqData)
  })
_sym_db.RegisterMessage(StreamReqData)

StreamResData = _reflection.GeneratedProtocolMessageType('StreamResData', (_message.Message,), {
  'DESCRIPTOR' : _STREAMRESDATA,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamResData)
  })
_sym_db.RegisterMessage(StreamResData)


DESCRIPTOR._options = None

_JREETER = _descriptor.ServiceDescriptor(
  name='Jreeter',
  full_name='Jreeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=79,
  serialized_end=231,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStream',
    full_name='Jreeter.GetStream',
    index=0,
    containing_service=None,
    input_type=_STREAMREQDATA,
    output_type=_STREAMRESDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PutStream',
    full_name='Jreeter.PutStream',
    index=1,
    containing_service=None,
    input_type=_STREAMREQDATA,
    output_type=_STREAMRESDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AllStream',
    full_name='Jreeter.AllStream',
    index=2,
    containing_service=None,
    input_type=_STREAMREQDATA,
    output_type=_STREAMRESDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JREETER)

DESCRIPTOR.services_by_name['Jreeter'] = _JREETER

# @@protoc_insertion_point(module_scope)
